### ISSUE TITLE
sandbox links are broken

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint-sandbox#1]
https://sandbox.mint-lang.com/sandboxes/N0iQTG1fduXoRA

This link is broken, but you can navigate to it by going to https://sandbox.mint-lang.com and then clicking on `Websocket Provider`

**Comment by s0kil** [comment]
@gdotdesign The `https://sandbox.mint-lang.com` points into this repo? Or the website repo? I could set up a file for Netlify.

**Comment by gdotdesign** [comment]
It's connected to this repo.
