### ISSUE TITLE
Selectable Mint version

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint-sandbox#6]
Used version is static and not labelled on the page

The sandbox is useful for linking snippets when reporting issues, but we can't, for example, test fixes on master branch

Additionally, this can lead to duplicates in reported issues and requires the user to install _mint@master_ locally to perform this tests

**Comment by gdotdesign** [comment]
After the next release, the version of the sandboxes can be set 1b3d60a88a38fca7e5403990fa532af58c2bc45a
